version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: petgram-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=petgram
    ports:
      - "5432:5432"
    networks:
      - petgram-network

  localstack:
    image: localstack/localstack:3.0
    container_name: petgram-localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services
    environment:
      - DEBUG=0
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - localstack_data:/var/lib/localstack
    networks:
      - petgram-network

networks:
  petgram-network:
    driver: bridge

volumes:
  postgres_data:
  localstack_data:
